rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/autotest
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/backendUpgrade
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/BrickTerminator
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/dlmalloc
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/fastlz
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/iniparser
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/m3d
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/MBacktrace
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/mdroid
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/MMAPInfo
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/moduletest
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/ramLog
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/muf/ipc
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/muf/Makefile
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/muf/native
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/muf/simulator
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/muf/tvos/arm-uclibc
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/core/muf/tvos/arm-gnueabi
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/Android.mk
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/documentation
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/mide
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/sn_rc.sh_SUDO
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/sn_release_to_cus.mk
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/tvos_rel_sys
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/\[Version\ Tool\]\ ReadMe.txt
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/file_list.txt
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/MStarSDK
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/SN_Changelist.txt
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/sn_release_china.sh
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/target
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/unittest
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/develop
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/MDebug
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/Policy.txt
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/sn_rc.sh
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/sn_release_cus.sh
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/tee
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/Version_Control.pl
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/build_atsc.sh
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/config
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/devices
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/Doxygen
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/ipc_svc
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/measure_build_time.sh
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/secure_map_transfer.pl
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/template
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/var_common.mk
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/board
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/buildsettings
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/customerinfo
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/dfbinfo
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/env.cfg
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/lint
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/sw_cfg
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/buildall.sh
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/check_library_flag.pl
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/customization
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/dfbinput
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/gdbcmd
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/Makefile
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/remove_code_for_release.sh
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/systeminfo
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/ui
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvatsc
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvatv
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvautotest
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvbrowser_service
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvcontrol
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvdvb
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvmodule_rel
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvmoduletest
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvmsrv.mk
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvmultimedia
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvMultiScreenTX
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvnetready
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvnetwork
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvsystem_database
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrvvvoip
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/Makefile
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/middleware
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/src
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/unittest
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_3DManager.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_Advert_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_AV_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_Backend.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_BacklightControl.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_CEC_Customer.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_CEC.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_ChannelManager.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_COMP_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_DivX_DRM.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_DTV_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_Factory_Mode.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MFSTypes.hMSrv_HDMI_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_HDMITX.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_LoadingLogo.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_MHL.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_MountNotifier.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_MWE.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_PC_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_Picture.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_PreSharedKey.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_RecordingScheduler.BookingDetails.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_RecordingScheduler.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_RVU_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_SCART_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_SrcDetect.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_SSSound.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_Storage_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_SV_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_Timer.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_TV_Player.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_UartDebug.h
rm -rf $ANDROID_BUILD_TOP/vendor/mstar/supernova/projects/msrv/common/inc/MSrv_Video.h
